### ISSUE TITLE
[BUG] filterDropdown props under Table.column not working with single select

### ISSUE THREAD

**Issue by emehmet** [refinedev/refine#3124]
### Describe the bug

When I use Select without multiple mode(so single select) under filterDropdown this is not filtered.

### Steps To Reproduce

You can create single select under the filterDropDown and you will see this is not trigger re-render query.
I think reason of this is antd filter is working with array only.

### Expected behavior

When I create single select it must work properly. But nothing happening. there is no any error.

**Comment by omeraplak** [comment]
Hey @emehmet ,
Can you share a StackBlitz env where we can reproduce the error?

**Comment by emehmet** [comment]
Hey @omeraplak,
of course,

https://stackblitz.com/edit/refinedev-refine-bcmbg1?file=package.json,src%2Fpages%2Fposts%2Flist.tsx&preset=node

I changed category select filter on table.column. Works on first selection but not after

**Comment by leapful** [comment]
@emehmet @omeraplak @aliemir @salihozdemir 

By default, Ant Design expected filtered keys should be an array or string but in case value is a number, it will be treated as invalid and stop on filtering.

A workaround on mapping number value to string value will help to solve this issue.

Workaround demo: https://stackblitz.com/edit/refinedev-refine-jydkgh?file=src%2Fpages%2Fposts%2Flist.tsx&preset=node

In case to support number value, please help to review this pull request : https://github.com/refinedev/refine/pull/3216

**Comment by omeraplak** [comment]
Hey @emehmet ,
Yes, it looks like Ant Design wants us to use it that way 😅

**Comment by omeraplak** [comment]
Hey @emehmet ,
Everything seems to be working with the latest (3.70.0) version. Is there something I missed?

Example: https://stackblitz.com/edit/refinedev-refine-daabnp?file=src%2Fpages%2Fposts%2Flist.tsx,package.json&preset=node

**Comment by leapful** [comment]
@emehmet

Did you mean the workaround in stackblitz or the new change from my PR https://github.com/refinedev/refine/pull/3216? 

After the PR, there is no need to use string type for single Select component. 

For case default select, you have to apply the `mapValue` on FilterDropdown to map selected keys in String to Number because Ant Design always normalizes selected keys to string value but its mapping for `options` is still using key as number value and caused wrong label for selected value on UI. That's why we need to provide `mapValue`.

**Comment by emehmet** [comment]
Hi @omeraplak @leapful 
I shared an ss with you. And a link to a stackblitz fork with defaultFiltedValue added.

https://ibb.co/GkNzVMd

https://stackblitz.com/edit/refinedev-refine-onx7tz?file=src%2Fpages%2Fposts%2Flist.tsx,package.json&preset=node

As you can see in the picture, when the default filter is assigned, the selected values appear as labels. There is no label. And there is nothing selected in the list. When we use this structure as a single select, if the value is number, the filter selects it, but the green lamp does not turn on.

**Comment by leapful** [comment]
@emehmet 

The problem is not related to the new changes of PR #3216. 

Like I said before, Ant Design builds a map option value based on the input `options` with key is the value, in this case, key is number but then when getting default value that is synced on query params of URL, it's always a string. It's really hard for the library to know which value in query params should be number or string, therefore a "mapValue" for FilterDropdown will be needed in order to normalize the type of value.

Working demo: https://stackblitz.com/edit/refinedev-refine-2tkgjs?file=src%2Fpages%2Fposts%2Flist.tsx,package.json&preset=node

**Comment by emehmet** [comment]
Hi @leapful 

I understand what you mean. However, the use of the component I want to tell varies according to the data type of the value. So if value is string, according to your solution, mapValue should not be used. It matches both. If Number comes, we have to make Number again with mapValue since you converted it to string in your update. 

@omeraplak 
If it will be used like this, you need to tell the developer about it in your documents.

**Comment by omeraplak** [comment]
Hey @emehmet ,
Does this document cover use cases? If not, can you contribute to this document? Thank you ⚡️

https://refine.dev/docs/api-reference/antd/components/filter-dropdown/#mapvalue

**Comment by emehmet** [comment]
Hi @omeraplak 

I think that the whole structure should be evaluated from the beginning rather than documenting the variations here. The return value may not matter the type in Http request. But for Graphql users, type is important. Or any typed query mechanism. In addition, since  the single select is no an array, the return type is a continuous string anyway. But it can be number in graphql query. We can't set this with mapValue at the moment.

If this is to be solved with another normalization, it seems that there will be no end to the variations.

I would love to contribute to the development of this, but I have some work to finish.
