### ISSUE TITLE
[BUG] Refine Antd + Vite fails in production build

### ISSUE THREAD

**Issue by nirga** [refinedev/refine#3187]
### Describe the bug

I think it's an issue similar to https://bytemeta.vip/repo/rjsf-team/react-jsonschema-form/issues/2962

When building a project with Refine/Antd and Vite there's an error on the browser `generatePickerExports is not a function`. 
It seems that the issue is due to imports from CommonJS modules in AntD and not ESModules as vite requires.

I've patched node_modules/@pankod/refine-antd/dist/esm/index.js to make it work (replacing picker imports from `lib` to `es` and it seem to resolve the issue.

### Steps To Reproduce

1. Create a new refine project with Antd and Vite.
2. Set `  build: {
    minify: false
  },` in `vite.config.ts`.
3. `npm run build`
4. `npm run preview`
5. Open a browser and see the error

### Expected behavior

Production build should work.

### Desktop

- OS: Mac OS 13
- Chrome 108
- Deployment with Vercel

**Comment by leapful** [comment]
@nirga @omeraplak @aliemir @yildirayunlu 

It seems the problem is not from importing CommonJS modules but from Vite version >= 3.0.0 (including latest version 4.0.0). If you downgrade Vite to verion 2.9.15, everything is fine.

By default, Vite already tried to transform CommonJS to ESM. But with version >= 3.0.0, the transform output has changed and caused wrong extraction `exports.default` for this specific use case of library `ant-design`.

For example, `ant-design` is trying to export default a function `generatePicker` and the result of calling `generatePicker` also returns a Functional React component.

https://github.com/ant-design/ant-design/blob/master/components/date-picker/generatePicker/index.tsx

**Output Vite 2.9.15**
```
function getDefaultExportFromCjs(x2) {
  return x2 && x2.__esModule && Object.prototype.hasOwnProperty.call(x2, "default") ? x2["default"] : x2;
}

...

var qo = /* @__PURE__ */ getDefaultExportFromCjs(generatePicker);

```

**Output Vite >= 3.0.0**

```
function requireGeneratePicker() {
   ...  
  
  //  IIFE to build data for generatePicker
  (function (exports2) {
   ....
  })(generatePicker)
  
 
  return generatePicker; // This is an object
} 

...

var generatePickerExports = requireGeneratePicker();

...

var $o = generatePickerExports(default_1); // This is not a function anymore

```

**Comment by omeraplak** [comment]
Hey,
We will release antd@5 support this week. Could this problem be solved with @5? @yildirayunlu can you test it?

**Comment by omeraplak** [comment]
Hey @leapful ,
I hope you are very well. It seems we are having the same issue on antd@5. Does have an idea about the best practice we should follow on this issue? 
Example issue: https://github.com/ant-design/pro-components/issues/6338

**Comment by nirga** [comment]
Hey all,
Have you seen https://bytemeta.vip/repo/rjsf-team/react-jsonschema-form/issues/2962? It seems that this issue related to how we import Ant in Refine, so it's unrelated to Ant's version

**Comment by leapful** [comment]
@nirga @omeraplak 

In summary, the root cause is from Vite > 3.0.0 (related to Vite's dependency Rollup too) which changed to way transforming CJS to ESM that causes default export is not following normal convention.

You can find the discussion here: https://github.com/vitejs/vite/issues/2139

Workaround can be changed import path from "lib" (CJS) to "es" (ESM) or patch "default export".

```
import { Dayjs } from "dayjs";
import dayjsGenerateConfig from "rc-picker/lib/generate/dayjs";
import generatePicker from "antd/lib/date-picker/generatePicker";

// https://gist.github.com/cedeber/83e5900085db1f61f940939d05f845ee
function interopDefault<T>(value: T): T {
    // all "vite build" modes (preview mode is in DEV mode)
    return import.meta.env.PROD || import.meta.env.MODE === "preview" ? (value as any).default : value;
}

const DatePickerComponent = interopDefault(generatePicker)<Dayjs>(dayjsGenerateConfig);

export default DatePickerComponent;

```

**Comment by aliemir** [comment]
Hey @nirga, just opened a PR to replace `/lib/` imports related to this issue (all of them actually 😅) with `/es/` ones in `@pankod/refine-antd`'s `ESM` builds. Just replacing the import was not enough for our case because we needed to keep the `/lib/` for the CJS builds. 

@leapful thank you for your comments! Would love to see your and @nirga's review for the PR #3252 🚀

**Comment by omeraplak** [comment]
Hey,
We've fixed this issue. Thank you @nirga @aliemir @leapful 🚀
