### ISSUE TITLE
[BUG] useFieldArray's update() and replace() reset dirtyfields in Edit View

### ISSUE THREAD

**Issue by capsloq** [refinedev/refine#3290]
### Describe the bug

When using update() or replace() method from `useFieldArray`. The dirtyfields do get reset while in `<Edit>` View which seems wrong. **However**, the same scenario but wrapped in `<Create>` does work.

### Steps To Reproduce

Visit codesandbox i prepared: https://codesandbox.io/p/github/capsloq/form-react-hook-form-use-steps-form

1. Click Create Post
2. Type something into Title Field
3. Go To Step 2 by clicking Next
4. Click "klick this to use update()" button
5. Notice that title is still dirty after clicking the button  ✅
6. If you go back to Step 1 you will see that the Title you typed is still there.

Now go back to all posts  (/posts)
1. Click on the Edit Button of one post
2. Type something into Title Field
3. Go To Step 2 by clicking Next
4. Click "klick this to use update()" button
5. Notice that title is not dirty anymore after clicking the button and the value form Step 1 is lost ❌

### Expected behavior

Keep values & dirtyfields when navigating through steps.

### Additional Context

Is that intentional or whats happening here?
I was not able to reproduce that with the original react-hook-form.

Thank you

**Comment by omeraplak** [comment]
Hey @capsloq ,
I think it's because the `update` function doesn't work in a partial way. In their documentation, it is recommended to use the `setValue` function to avoid such side effects. https://react-hook-form.com/api/usefieldarray/#main

I tried on your example, it seems to work:  https://codesandbox.io/p/github/capsloq/form-react-hook-form-use-steps-form/csb-17uosb/draft/late-feather?file=%2Fsrc%2Fpages%2Fposts%2Fedit.tsx&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A64%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A64%7D%5D

I saw that we reset the values in step changes but the good news is we have a PR that fixed it: #3307

**Comment by capsloq** [comment]
Hello @omeraplak,
thank you for looking into it.
I am using setValue in my project and can confirm that setValue is working correctly in all scenarios.
I got a  bit worried when i read that setValue will be removed for replacing entire field arrays in the next version:
`Important: use [replace](https://react-hook-form.com/api/usefieldarray#replace) from useFieldArray instead, update entire field array with setValue will be removed in the next major version.`  https://react-hook-form.com/api/useform/setvalue

Thank you for the fix as well!
