### ISSUE TITLE
[DOC] How to implement many-to-many relationships (Supabase)

### ISSUE THREAD

**Issue by MetaCorp** [refinedev/refine#3327]
### Documentation issue

I'm using supabase and I can't find somewhere in the docs talking about many-to-many relationships.

### Describe the thing to improve

How to implement many-to-many relationships in refine ?

Same as the example from the doc, where a `post` is linked to a `category`, but this is a one-to-many relationship, I need a many-to-many relationship, so a `post` linked to many `categories`.

I would also need to know how to filter by `posts` by `categories` in a many-to-many relationship.

**Comment by aliemir** [comment]
Hey @MetaCorp, thank you for the issue! We have [this section(handling-many-to-many-relationships)](https://refine.dev/docs/advanced-tutorials/data-provider/supabase/#select---handling-many-to-many-relationships) in our Supabase docs. This is kind of overlooked because we don't explain the tables and their structures well and `!inner` might not be required, let me try to explain it here and we will also update the docs soon.

`movies` table: `id(primary), title`
`categories` table: `id(primary), name`
`categories_movies` table: `category_id(primary), movie_id(primary)` (a compose primary key with both of the columns)

Let's have some sample data like;

**movies**
```
| id | title           |
|----|-----------------|
| 1  | the green mile  |
|----|-----------------|
```

**categories**
```
| id | name           |
|----|----------------|
| 1  | drama          |
| 2  | mystery        |
|----|----------------|
```

**categories_movies**
```
| category_id | movie_id |
|-------------|----------|
| 1           | 1        |
| 2           | 1        |
|-------------|----------|
```

In our `useTable`(or similar), we need to add `metaData.select` like;

```jsx
useTable({
  metaData: {
    select: "*, categories(name)",
  }
});
```

Since we have the relations defined in `categories_movies` table with composite primary key, we will be able to retrieve the data in our response with `categories` field as an array of values (`categories: [{ name: "drama" }, { name: "mystery" }]`)

You can check out the Supabase's example here https://supabase.com/docs/reference/javascript/select at "Query foreign tables through a join table" tab.

**note**: Defining a composite primary key with both `category_id` and `post_id` is required for this select expression to work.

**Comment by aliemir** [comment]
We'll update the documentation to show this usage and update the example to have a many-to-many field

**Comment by MetaCorp** [comment]
Thank you, I'm able to retrieve data from supabase this way.

I want to add `post` with `categories` from the `post/create.tsx` page.
I'm using mui and right now, I'm testing with this component :
```javascript
<Controller
      control={control}
      name="categories"
      // rules={{ required: "Category is required" }}
      render={({ field }) => (
          <Autocomplete
              {...autocompleteProps}
              {...field}
              multiple
              onChange={(_, value) => {
                  field.onChange(value);
              }}
              getOptionLabel={(item) => {
                  return item.title ? item.title : "";
              }}
              isOptionEqualToValue={(option, value) =>
                  value === undefined || option.id === value.id
              }
              renderInput={(params) => (
                  <TextField
                      {...params}
                      label="Categories"
                      margin="normal"
                      variant="outlined"
                      error={!!errors.categories}
                      helperText={errors.categories?.message}
                      required
                  />
              )}
          />
      )}
/>
```
But I have this error : `column "categories" of relation "posts" does not exist`.
I understand that I have no `categories` field for `post` in supabase, but how to tell refine the relationship when creating data from the `post/create.tsx` page ?

**Comment by aliemir** [comment]
Hey @MetaCorp, you can check out this doc https://refine.dev/docs/packages/documentation/react-hook-form/useForm/#how-can-i-change-the-form-data-before-submitting-it-to-the-api

Supabase throws an error because it can't find `categories` column in the `posts` table, since there is really no such column, you need to remove that field before submitting the form and send create requests to the `posts_categories` table using `useCreate`(or `useCreateMany` for your case) separately.

Closing this issue for now, if you have any trouble while using `useCreate` or `useCreateMany` please reach out! 🚀

**Comment by MetaCorp** [comment]
Hey again @aliemir,
I'm trying to implement filtering by categories in this many-to-many relationship. How can I do so with Refine ? What would be the `field` of the filter ?

**Comment by rawkode** [comment]
@MetaCorp did you ever get this working?

**Comment by endrit-mesh** [comment]
Hi @rawkode, I asking you the same question :) did you ever get this working? Because right now I'm also in the same spot

**Comment by rawkode** [comment]
Unfortunately not, I tried getting help here and on Discord; but no success. 

Good luck!

**Comment by endrit-mesh** [comment]
@rawkode, I just found a workaround for this issue. I have attached the code which essentially explains the solution itself. It appears that with many-to-many relationships, we need to add !inner inside the select statement. I created a state with a default value and used useEffect to change the select value when the filter value changes. Here’s the revised code:

```typescript
const [selectValue, setSelectValue] = React.useState<string>(
    "*, phone_numbers(*), tags(id, name)"
  );
 const { tableProps, tableQueryResult, filters } = useTable({
    resource: "contacts",
    meta: {
      select: selectValue,
    },
    sorters: {
      initial: [
        {
          field: "id",
          order: "desc",
        },
      ],
    },
    syncWithLocation: true,
    filters: {
      initial: [
        {
          field: "type",
          value: undefined,
          operator: "in",
        },
        {
          field: "tags.id",
          value: undefined,
          operator: "in",
        },
      ],
    },
    onSearch: (values: any) => {
      return [
        {
          field: "firstname",
          operator: "contains",
          value: values.name,
        },
      ];
    },
  });
  useEffect(() => {
    if (filters.find((item: any) => item.field == "tags.id")?.value) {
      setSelectValue("*, phone_numbers(*), tags!inner(id, name)");
    } else {
      setSelectValue("*, phone_numbers(*), tags(id, name)");
    }
  }, [filters.find((item: any) => item.field == "tags.id")?.value]);
```
