### ISSUE TITLE
[BUG] Navigate backwards twice when redefining goBack prop from Create element

### ISSUE THREAD

**Issue by joanaavelar** [refinedev/refine#3358]
### Describe the bug

Clicking on the newly created back arrow component from a Create page, is redirecting the solution not to the previous page, but to the previous previous page.

### Steps To Reproduce

1. Install the dependencies - npm install
2. npm start
3. Land on Dash One List page
4. Navigate to Dash Two List page
5. Click on Create button from Dash Two List page - you should be redirected to Create Dash Two List page
6. Click on the back button from Create Dash Two Page
7. You should go back to Dash Two List page, instead you are redirected to Dash One List page

### Expected behavior

Following the steps described above, the expected behaviour should be to go to Dash Two List Page.
Looking at the documentation: [https://refine.dev/docs/api-reference/mui/components/basic-views/create/#goback](url) the expected behaviour should be possible.
Internally, the component is doing an extra **navigate.goBack()** which is causing this issue.

### Additional Context

Please consider the sample zip attached.
[sample.zip](https://github.com/refinedev/refine/files/10359087/sample.zip)

**Comment by aliemir** [comment]
Hey @joanaavelar sorry for the issue. 

Checked your sample and saw you're using `@pankod/refine-antd` from v3 version. We've upgraded the package to support `antd@5` and our docs follow the latest version. 

For your issue, there's a change in behavior between those packages. In the latest version, `goBack` prop replaces the default goBack element (with its onclick and everything). In the previous versions (<= v3), `antd` was giving two different props to change the back button, one was the icon (which we supply by the `goBack` props) and the other was to change the onclick handler when you click on this button. Therefore, the `goBack` prop was presented as the icon element of the button (so the onclick was handled internally). In the latest version, this issue is resolved and `goBack` replaces the whole element not just the icon.

Possible solutions;

1) You can upgrade to the latest version (If you want to, please check the migration guide here https://refine.dev/docs/api-reference/antd/migration-guide/v4-to-v5/)
2) If you don't want to override the button functionality and just change the icon, update your `goBack` prop accordingly.
3) If you want to change the go back functionality too, then `event.stopPropagation` and `event.preventDefault` should resolve your issue when you provide them in your `onClick` callback.

**Comment by joanaavelar** [comment]
Sorry, I forgot to reply back. 
Thanks for the detailed explanation.
I tried your first suggestion and it worked like a charm. 
Thanks again for your help.
