### ISSUE TITLE
[BUG] Material UI notification popups twice

### ISSUE THREAD

**Issue by hanifmianjee10p** [refinedev/refine#3392]
### Describe the bug

The pop-up is appearing twice when I go to an edit resource page and the resource ID does not exist in the database. It retries multiple times and eventually fails with duplicate toast messages.

/posts/edit/100

Where ID 100 doesn't exist in the database.

I am using **RefineSnackbarProvider from @pankod/refine-mui**

@alicanerdurmaz Here is the issue that we discussed in the Discord server

### Steps To Reproduce

1. Goto /posts/edit/100000
2. Where ID 100000 doesn't exist in the database
3. Wait for a couple of seconds for multiple retries
4. Notice the duplicate toast popups

### Expected behavior

Notification should trigger only once

**Comment by alicanerdurmaz** [comment]
@hanifmianjee10p Hi again,

This issue happens because `useQuery`'s `onError` function is called when we don't want it.

We talked to the core team. We considered a few workarounds but ultimately decided to consult the TanStack community as well. [issue on TanStack Query](https://github.com/TanStack/query/issues/4827)

We will publish the fix with the best practice in the fastest time. I will keep inform you about updates. Thanks again 🙏

**Comment by ALIRAZA17** [comment]
@omeraplak Can I work on this one?
