### ISSUE TITLE
[BUG] useCreateMany mutate onSuccess is not called

### ISSUE THREAD

**Issue by MetaCorp** [refinedev/refine#3415]
### Describe the bug

`useCreateMany` `mutate` `onSuccess` is not called

### Steps To Reproduce

```typescript
const { mutate } = useCreateMany<any>();

// ...

mutate({
  ressource: "categories",
  values: [...]
}, {
  onSuccess: (data: any) => {
    // not being called
  }
})

```

`onError` is not being called either

### Expected behavior

`onSuccess` called when the mutation succeeds.

**Comment by omeraplak** [comment]
Hey @MetaCorp ,
Unfortunately, I could not reproduce the issue :(

CodeSandbox: https://codesandbox.io/s/h1w6dn?file=/src/pages/posts/list.tsx:356-378

**Comment by omeraplak** [comment]
If the problem persists, could you please reopen the issue?

**Comment by MetaCorp** [comment]
Hey @omeraplak ,

I have modified your CodeSandbox, demonstrating the bug in create.tsx

CodeSandbox: https://codesandbox.io/s/base-headless-forked-ubxnev?file=/src/pages/posts/create.tsx

**Comment by omeraplak** [comment]
Hey @MetaCorp ,
The reason for this is that your form hook redirects before waiting for the mutate operation, and as a result, the "onSuccess" event cannot be triggered because the component is destroyed from the browser DOM during the redirect process. But don't worry, I have created an example for you.

https://codesandbox.io/s/base-headless-forked-eit328?file=/src/pages/posts/create.tsx
