### ISSUE TITLE
[BUG] Custom Resources Label with Inferencer component

### ISSUE THREAD

**Issue by JerryLiu19880810** [refinedev/refine#3435]
### Describe the bug

ℹ️ Information 
UI Framework: Ant Design
dataProvider: Supabase 

🐞 Bug description
while set Chinese in `label`
![圖片](https://user-images.githubusercontent.com/9213776/213867723-2ec4a502-7df8-48f5-8569-c20b705c17b2.png)

the page will result in Error
![圖片](https://user-images.githubusercontent.com/9213776/213867767-e1cb21a7-6333-44a6-b60f-d6ed21f45875.png)

### Steps To Reproduce

1. custom resources
2. type some Chinese like "下包管理" in `label` 
3. refresh the page

### Expected behavior

should show the table like this
![圖片](https://user-images.githubusercontent.com/9213776/213867941-4d195e76-5f1a-47ee-93e7-378705f13a40.png)

**Comment by wombat86** [comment]
I'm experiencing the same issue but with Cyrillic label. Looks like only English text works fine with `"label"` property. This probably has to do something with encoding IMHO.

**Comment by wombat86** [comment]
Okay, I found a root cause.

Inferencer generates the code for the list component. It generates a name for the component variable and uses it in the component code [template](https://github.com/refinedev/refine/blob/1e3c467a95c049c8cc1defb09f8f1df0e6ebcb50/packages/inferencer/src/inferencers/antd/list.tsx#L528). When generating the variable name, it [uses](https://github.com/refinedev/refine/blob/1e3c467a95c049c8cc1defb09f8f1df0e6ebcb50/packages/inferencer/src/inferencers/antd/list.tsx#L31) `resource.label` if it is present rather than `resource.name` as a prefix. After that it performs an identifier name [sanitization](https://github.com/refinedev/refine/blob/1e3c467a95c049c8cc1defb09f8f1df0e6ebcb50/packages/inferencer/src/utilities/component-name/index.ts#L13) which strips all characters that do not match `[a-zA-Z]`. Thus, our target component name looses prefix entirely and we end up having `List` as the list component name. However, another `List` variable already exists in the context because it is being imported from `@pankod/refine-antd`.

**Comment by aliemir** [comment]
Hey @JerryLiu19880810 and @wombat86, looks like a workaround is already found and applied 🙏 🚀  but just opened a PR (#3441) to fix this issue. Now the component name will fallback to `Inferred{Action}` in case of empty label or non `[a-zA-Z]`. 🧑‍🍳
