### ISSUE TITLE
[BUG] inferencer with multiple dataproviders don't work

### ISSUE THREAD

**Issue by kingofsevens** [refinedev/refine#3483]
### Describe the bug

When you use multiple data providers the influencer tries to detect but couldn't

### Steps To Reproduce

Below code doesn't work...

```javascript
<Refine
  routerProvider={routerProvider}
  dataProvider={{
    posts: dataProvider("https://api.fake-rest.refine.dev")
  }}
  resources={[
    {
      name: "posts",
      list: ChakraUIInferencer,
      show: ChakraUIInferencer,
      create: ChakraUIInferencer,
      edit: ChakraUIInferencer,
      options: {
        dataProviderName: "posts",
      },
    }
  ]}
/>
```

However below code works as expected.

```javascript
<Refine
  routerProvider={routerProvider}
  dataProvider={dataProvider("https://api.fake-rest.refine.dev")}
  resources={[
    {
      name: "posts",
      list: ChakraUIInferencer,
      show: ChakraUIInferencer,
      create: ChakraUIInferencer,
      edit: ChakraUIInferencer,
    }
  ]}
/>
```

### Expected behavior

To render the output.

**Comment by omeraplak** [comment]
Hey @kingofsevens ,
Thank you for reporting the issue. We'll fix it soon ⚡️

**Comment by aliemir** [comment]
Hey @kingofsevens, sorry for the issue but I think I can break it down the process here so we can clear the use here.

To use a multiple data provider, you need to define a `default` property as well. It's required by refine to handle resources without a specific data providers to fallback to that one. Here's the docs https://refine.dev/docs/api-reference/core/providers/data-provider/#using-multiple-data-providers

If the inferencer is erroring out, this might be the cause, since it can't find a proper data provider to handle the request, the process is going to fail. 

If you have different resources for the relations in your data (for example `posts` resource from `posts` data provider has a relation with `categories` resource of `my-other-data-provider`. In this case, you can define a `categories` resource in the `resources` array and pass `my-other-data-provider` in `options.dataProviderName`. Inferencer will use this config to send the requests for `categories` resource. 

If the issue is not about the above topic, please elaborate and share the output of the inferencer 🙏 We'll try to investigate and resolve the buggy behavior if there is one.
