### ISSUE TITLE
[BUG] refine-kbar doesn't show all actions on initial load

### ISSUE THREAD

**Issue by smparekh** [refinedev/refine#3484]
### Describe the bug

when using refine-kbar on the dashboard not all actions that are available for the user. After navigating to another page more actions are available but not all.

### Steps To Reproduce

n/a

### Expected behavior

All actions that are permitted for that user should be available in all pages / contexts.

### Screenshot

<img width="603" alt="Screenshot 2023-01-28 at 12 50 00" src="https://user-images.githubusercontent.com/2242057/215283085-f07769b5-5238-464f-a4fa-3fb176f3d5c0.png">
<img width="603" alt="Screenshot 2023-01-28 at 12 50 18" src="https://user-images.githubusercontent.com/2242057/215283089-112941ad-77fc-46b2-8810-fb7bfae710d2.png">

### Desktop

Browser: 108.0.2 (64-bit)
Version: refine-kbar 0.10.2

### Additional Context

```typescript
    <RefineKbarProvider>
        <Refine
          routerProvider={{
            ...routerProvider,
          }}
          notificationProvider={notificationProvider}
          dataProvider={dataProvider(hasuraClient)}
          accessControlProvider={{
            can: async ({ resource, action, params }) => {
              if (role == "system_administrator") {
                return Promise.resolve({
                  can: true,
                });
              }
              if (
                role in PermissionsMap &&
                resource in PermissionsMap[role] &&
                PermissionsMap[role][resource].includes(action)
              ) {
                if (
                  resource == "users" &&
                  role == "operator" &&
                  action == "edit"
                ) {
                  if (params && params.id == user.sub) {
                    return Promise.resolve({
                      can: true,
                    });
                  } else {
                    return Promise.resolve({
                      can: false,
                      message: "Unauthorized",
                    });
                  }
                }
                return Promise.resolve({
                  can: true,
                });
              }
              return Promise.resolve({ can: false, message: "Unauthorized" });
            },
          }}
          Title={Title}
          Header={Header}
          Sider={Sider}
          Footer={Footer}
          Layout={Layout}
          resources={resources}
          catchAll={<ErrorComponent />}
          DashboardPage={DashboardPage}
          OffLayoutArea={OffLayoutArea}
          options={{
            disableTelemetry: true,
          }}
        >
          {children}
        </Refine>
      </RefineKbarProvider>
```

**Comment by aliemir** [comment]
Hey @smparekh sorry for the issue. Checking it now, hopefully we'll find the issue and fix it soon 🙏 

I have couple of questions that might help us figure out

Do you have nested resources like ones with `parentName` property?
Do you load your resources asynchronously?
Do you think `accessControlProvider` might have a part on this issue?
Do you have a chance to (just for testing) comment out the access control provider and try again to see if the actions are listed as expected?

**Comment by smparekh** [comment]
Hey @aliemir 

1. yes we do have resources with `parentName` property
2. we do not load resources asynchronously
3. that is what I think as well, there is some interaction with `accessControlProvider` and kbar that I do not understand
4. commenting out didn't make a difference

**Comment by aliemir** [comment]
About the predefined actions, we're defining actions depending on the `resources` array and by default we can show the actions `List` and `Create` for the resource because `Edit` and `Show` depends on the `id` and since we thought it might lead to unintended behaviors/errors we don't create actions for those (since they will be magically appear and hard to customize). 

If `list` is not provided to a resource item, then `List` action won't be shown. (same applies to others). When you navigate to a details page or an edit page we also provide `delete`, `show` or `edit` actions since `id` is inferred from the URL. 

Actually this is all we provide by default, you can of course create your own actions and append to the actions list. (Check out https://refine.dev/docs/packages/documentation/command-palette/#custom-actions)

We have this example here https://refine.dev/docs/examples/command-palette/ you can use to create a reproduction for your case (or can you provide us the structure of your resources, you can remove any sensitive/confidential data or labels, we just wanted to check the structure to be able to test the issue)

I also created a basic example with custom actions, I added a simple action creation logic in `/posts` route and added all items in the table to the command palette, giving users the ability to navigate to show and edit pages of those items. Here's the sandbox: https://codesandbox.io/s/nostalgic-northcutt-pcmufp?file=/src/pages/posts/list.tsx

(`createAction` is used in the docs but not in my example, and that helper is only adding unique `id` to the actions which is handled manually in the example)

Also I've noticed some issue with the `parentName` property, which `refine-kbar` lacks the checking of it. We're moving the active resource to the top of the actions list to show it first but with `parentName` this one fails. I'll try to release a quick fix for it by mentioning this issue 🤔 

Thank you for your patience.

**Comment by smparekh** [comment]
Thanks @aliemir, i will take a look at your example, we do indeed use parentName to logically group the resources. I wonder if your fix to the that issue will work for this as well. Let me know when a newer version is released so I can test it out in our dev environment.
