### ISSUE TITLE
[BUG] Limit to 5000 documents when loading from AppWrite by dataProvider

### ISSUE THREAD

**Issue by bimupmup** [refinedev/refine#3563]
### Describe the bug

 When I get data from appwrite in backend which had more than 100k+ record, APi only return exactly 5000 documents. I want to load all data frrom collections to my font end. Please help me with this. Tks

### Steps To Reproduce

Hi

### Expected behavior

Load all documents in collection to web
Display them by pagination

**Comment by alicanerdurmaz** [comment]
@bimupmup, this issue is not related to **refine**. 

[You can read AppWrite doc for more information](https://appwrite.io/docs/pagination)
`The maximum offset is 5000, since the request gets slower as the number of records increases because the database has to read up to the offset number of rows to know where it should start selecting data.`


I think you should open an issue on AppWrite GitHub. Maybe they can offer a solution.
