### ISSUE TITLE
[BUG] Date inference too sensitive

### ISSUE THREAD

**Issue by YechiamTK** [refinedev/refine#3635]
### Describe the bug

Hi :)

In one of my resources I have a string field that for some reason the Inferencer recognizes as a date field.
The field values can be, for example: "112312", "551351", "34223", "2222" etc. The sole rule of this field that I can say for sure is that it is a string representation of a number with minimum 4 letters.

It gets inferred as date and so gives values such as "12/01/1123," "01/01/3333", "02/02/202" etc.

### Steps To Reproduce

Not really sure what triggers this, but perhaps the value the Inferencer tries to infer from is at a length that seems reasonable for the inferring to be date; or even that when a string is only numbers the inferring is automatically date.

Anyway the reproduction is having a field of type string with number values with length of at least 4 letters.

### Expected behavior

Should be inferred as string or number, not date.

### Screenshot

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17084820/219956581-47799a66-37b9-41f5-812e-2b1b19e05927.png)

### Additional Context

Discord discussion: https://discord.com/channels/837692625737613362/1076868034192486451

**Comment by aliemir** [comment]
Hey @YechiamTK sorry for the issue. Looks like @BatuhanW sent a PR to fix this (#3636)

I think the root cause for this issue was, while adding the inference function for date fields, we thought it would be a good idea to support unix time and had this check but looks like this is causing more issues than it resolves 🤣 

Sorry again for the issue, we'll have a review for the PR and hopefully release version with the fix very soon 🙏
