### ISSUE TITLE
[DOC] How to use useDelete when the table has no id

### ISSUE THREAD

**Issue by MetaCorp** [refinedev/refine#3788]
### Documentation issue

https://refine.dev/docs/api-reference/core/hooks/data/useDelete/

### Describe the thing to improve

I'm using Supabase, and I have a join table `posts_likes` with composite primary key ( `post_id` + `profile_id` ). So I have no id field on the record being stored.

How can I use useDelete with a composite primary key in Supabase since useDelete only accept an id ?

**Comment by BatuhanW** [comment]
Hello @MetaCorp

As you said, useDelete hook expects single ID since that's the %99+ of the cases.

My suggestion would be to use `supabaseClient` directly for removing data from the your API with your custom logic and use [useInvalidate hook](https://refine.dev/docs/api-reference/core/hooks/invalidate/useInvalidate/) to invalidate your resource data, so they'll be refetched.

Ideally, you can extract this logic into a custom hook with a name like `useDeleteWithCompositeKeys`, so it will look clean in your component.

If that answers your question, feel free to close the issue. 

Best

**Comment by BatuhanW** [comment]
Hello @MetaCorp, closing the issue as completed, feel free to re-open if it's needed.
