### ISSUE TITLE
[FEAT] Access user identity and permissions in access control provider

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3924]
### Is your feature request related to a problem? Please describe.

There should a way to access `usePermissions` and `useGetIdentity` in the `accessControlProvider` prop of `Refine` component.

### Describe the thing to improve

Add a way to access `usePermissions` and `useGetIdentity` in the `accessControlProvider` prop of `Refine` component.

**Comment by shaunbeh** [comment]
hey @BatuhanW ,
This method calls `getIdentity`/`getPermissions` four times for every resource, which feels wrong, especially for `getIdentity` since it has the same API response every time. React Query and caching are not available at the `app.tsx` level, so I created a `useUserStore`:

```jsx
const useUserStore = create((set) => ({
  userInfo: null,
  fetchUserInfo: async () => {
    try {
      const response = await customAxios.get('/api/userInfo');
      set({ userInfo: response.data });
    } catch (error) {
      console.error('Failed to fetch user info:', error);
    }
  },
}));
```

I then passed the `userInfo` in both `accessControlProvider` and `getIdentity`:

```jsx
const useAuthProvider = () => {
  const { userInfo } = useUserStore();
  return {
    getIdentity: async () => {
      return userInfo;
    },
  };
};
```

And called it above the return in `app.tsx`:

```jsx
const { userInfo, fetchUserInfo } = useUserStore();

useEffect(() => {
  fetchUserInfo();
}, [fetchUserInfo]);

if (!userInfo) {
  return <div>Loading...</div>;
}
```

Do you approve of this approach, or do you have a better way?
