### ISSUE TITLE
[DOC] Integration with Existing App?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [refinedev/refine#4038]
### Documentation issue

I don't see anything in the docs that describes how to integrate Refine with an already existing (e.g. Next.Js) application

### Describe the thing to improve

Is it even possible to really use the framework with an existing application? In certain situations (ours especially) we have an already deployed application for which we would love to add Refine as we are looking at the next phase of development that includes Admin & Reporting.

But everything I can see in the docs seems to imply that Refine wants to be used as its own standalone app

**Comment by BatuhanW** [comment]
Hello @mfreeman-xtivia, we have a task in our backlog to integrate into existing applications, and we'll release it soon.

However, since refine doesn't have any coupling with router, it shouldn't be different, other than perhaps creating an `admin` base route and wrapping it with `<Refine>` component.

Even though it's not very clear, for now, you can read the following docs to have some idea.

https://refine.dev/docs/packages/documentation/routers/nextjs/

And you can also see our example here: https://refine.dev/docs/examples/next-js/NextAuth.js/
