### ISSUE TITLE
[BUG] Multiple MUI Autocomplete not clearing previous search value

### ISSUE THREAD

**Issue by johnwards** [refinedev/refine#4164]
### Describe the bug

When using `multiple` prop on an MUI Autocomplete with refines `useAutocomplete` when you search for the next value after selecting the one you have found, the options returned are what you seen in the previous search. It clears it self when you start typing.

The default MUI component doesn't have this behaviour, you can try it out via their [docs](https://mui.com/material-ui/react-autocomplete/#multiple-values)

### Steps To Reproduce

1. Using tutorial edit the generated Categrory Autocomplete component for creating a blog post
2. You will have to not pass the `field` prop as it errors, and I don't know why, another bug?
3. Add the `multiple` prop to the Autocomplete component
4. Go to /blog-post/create
5. Type "non" in the Category and select the first option 
6. Click the Categrory option again, the same options will appear
7. If you type they will change

### Expected behavior

When clicking the component I'd expect the default list of options again, not the previous searched options.

### Screenshot

![image](https://user-images.githubusercontent.com/34269/231712399-c669fd64-1496-47d4-89d4-3ed21dc23a76.png)
![image](https://user-images.githubusercontent.com/34269/231712444-9a8bcc3f-e02f-4bc1-a7c7-d28f286c9ff6.png)
![image](https://user-images.githubusercontent.com/34269/231712481-af90f7f7-f124-491c-90ab-f1e96370a8da.png)

### Desktop

Chrome, on a mac book

**Comment by salihozdemir** [comment]
Hey @johnwards,

We'll investigate it next week. Please stay tuned!

**Comment by salihozdemir** [comment]
Hey @johnwards,

> You will have to not pass the field prop as it errors, and I don't know why, another bug?

It is not a bug. The errors related to type, when you pass the `multiple` attribute, <AutoComplete> expects to array field.


I have created a PR to fix this issue. It will be available in the next release. 🚀

Also, we noticed that the selected options can disappear while searching. Because the options come from the server, if selected options are not in the response, they will disappear. We created a task to fix this issue.

Thanks for the report. 🙏
