### ISSUE TITLE
[BUG] basepath support with NextJS

### ISSUE THREAD

**Issue by snird** [refinedev/refine#4206]
### Describe the bug

Refine modules ignore the `basepath` configuration for NextJS

### Steps To Reproduce

Fork the example app with NextJs, set `basepath` in the `next.config.js` to some subpath.

### Expected behavior

Have the refine link and router know about this configuration

### Screenshot

![image](https://user-images.githubusercontent.com/2139589/233190048-85e6bf84-5f09-4846-8a06-38fbf6ac62bc.png)

### Additional Context

This is not blocking the app from working (as far as I went), but it causes warnings and may cause errors going forward.

The "closest" issue to that, that I could find, is this: https://github.com/refinedev/refine/issues/3207 but it is unrelated to the NextJS issue.

**Comment by aliemir** [comment]
Hey @snird, I've tried to reproduce the issue and succeeded. This looks like a simple issue with the dev server 😅I started the `with-nextjs` example and added `basePath` to the `next.config.js` file and the error appeared (Only when using the deprecated `Layout` component of `@refinedev/antd`). Then, I restarted the server and the error is gone. I guess when you apply `basePath` while the server is running, Next adds the `basePath` configuration to the client side navigation successfully but on the server side it fails to apply it properly. That's why it disappears when you restart the server 😅 

Btw, we now recommend `ThemedLayoutV2` instead of the `Layout` component from `@refinedev/antd` 🚀 

Do not hesitate to re-open the issue if you can provide a repro even after re-starting the server 🙏

**Comment by snird** [comment]
@aliemir thank you for the response!
I appreciate the outstanding work you do here. Tahnk you!
