### ISSUE TITLE
[BUG]: Dependabot security alert for `@refinedev/cli@2.9.0` at `marked` dependency!

### ISSUE THREAD

**Issue by Mr0nline** [refinedev/refine#4899]
### Describe the bug

CLI is depended on marked npm package which has a security vulnerability. Can CLI update the dependency itself or we require adding latest `marked` package in `devDependencies` to resolve this security alert? (See attached screenshot)

### Steps To Reproduce

1. Have dependabot enabled into project with mentioned cli.
2. Go to security alerts to find out the above mentioned alert.

### Expected behavior

There should be no security alerts for internal dependencies.

### Screenshot

![image](https://github.com/refinedev/refine/assets/57582883/f84b9e4c-ffa5-4f92-b907-f52008c69b08)

**Comment by BatuhanW** [comment]
Hello @Mr0nline thanks for the issue. 

In order to fix this issue, we need to update `ink` package, but latest release of this library is ESM only, so we can't do this update immediately.

Also, `@refinedev/cli` package is not included into the bundle and only used on development environment and to start server. So I think it's not a major issue atm.

**Comment by Mr0nline** [comment]
I'll just make an exclusion for this warning as it won't be causing troubles in production!

@BatuhanW shall I close this issue then?

**Comment by aliemir** [comment]
Hey @Mr0nline, happy to see this has come to a conclusion. 🙏  We'll be looking for ways to replace `ink-markdown` which uses the `marked` under the hood. Closing this issue for now but we'll have a reference to it when we have a progress on the fix. 🚀
