### ISSUE TITLE
[BUG] Invalidation

### ISSUE THREAD

**Issue by colaquecez** [refinedev/refine#5125]
### Describe the bug

Hey guys, I'm trying to understand why sometimes the delete doesn't trigger the invalidate in order to refresh the list, you can see on this video that the first time is working, and the other ones aren't working(the API call is working for all the calls because I can see the API call in the network tab), it seems the invalidate + Optimistic aren't triggering.

Not necessarily the other attempts will not work, sometimes it does, it's kind of unpredictable

https://github.com/refinedev/refine/assets/38195454/299f2d2b-dc4c-4a25-8baa-0e0eb4a78f5b

### Steps To Reproduce

1. I delete 2 different items, the first one work

### Expected behavior

When the user presses delete it should call the api to delete it and then refresh the list

**Comment by omeraplak** [comment]
Hey @colaquecez ,
Thanks for reaching out to us. It's understandable to be confused about this, as our documentation doesn't explain this topic well. The good news is that we'll be updating our documentation soon to cover this topic in more detail.

The issue generally arises because if the resource value used by useTable doesn't match the resource value of the useDelete hook, then the user has to manage the invalidation.

So, if the useTable hook is using the "trial_participants" value and the useDelete hook takes a different value like "trial_participants_delete" as its resource, you can update your state using one of the two methods found at https://refine.dev/docs/faq/#how-can-i-refetch-data.

**Comment by colaquecez** [comment]
Hey @omeraplak, thank you for the help, I was checking and it seems the endpoint isn't waiting for the delete(when we delete it the backend just returns without settling the promise), that's why when I try to delete fast, this error is happening,  we invalidate the `list` but the query is returning faster than the delete.

**Comment by colaquecez** [comment]
![Screenshot 2023-10-18 at 2 23 13 PM](https://github.com/refinedev/refine/assets/38195454/513999ec-0620-4056-a06c-078a883cad8f)
![Screenshot 2023-10-18 at 2 23 21 PM](https://github.com/refinedev/refine/assets/38195454/557e299c-6ac3-4fe8-bfb6-4efd2404405e)
![Screenshot 2023-10-18 at 2 24 43 PM](https://github.com/refinedev/refine/assets/38195454/a89ff50d-a379-4c66-bf2a-5cb055a12073)


Although the backend is returning the information I am still having the same issue, and if the invalidation was wrong it wouldn't work in the first time, it only happen when I try to delete fast the items

**Comment by omeraplak** [comment]
Hey @colaquecez ,
I couldn't reproduce the issue in our Ant design example. If you can reproduce it using our example at [https://refine.dev/docs/examples/tutorial/antd-tutorial/], can you let us know? If not, could you provide us with a separate CodeSandbox link where we can replicate the problem?

**Comment by xzeggaedu** [comment]
The same happened to me, but with small differences, sometimes happens sometimes not, sudenly the view works perfectly and two minutes later it doesn't work. 

I am using invalidate because the resource on my table is different and I follow the documentation in for that kind of escenarios but nothing solve the issue.

  ```
const { query, result } = useList({
    resource: "users",
    queryOptions: {
      enabled: canAccess?.can ?? false,
    },
    successNotification: false,
    errorNotification: false,
  });

  const { mutate: softDeleteUser, mutation: deleteState } = useUpdate();
  const invalidate = useInvalidate();

  const handleDeleteUser = (userId: string, userName: string) => {
    softDeleteUser(
      {
        resource: "soft-delete",
        id: userId,
        values: { type: "user/uuid" },
        successNotification: false,
      },
      {
        onSuccess: async () => {
          invalidate({
            resource: "users",
            invalidates: ["all", "list"],
          });

          toast.success('Usuario movido a papelera', {
            description: `El usuario "${userName}" ha sido movido a la papelera de reciclaje.`,
            richColors: true,
          });
        },
        onError: (error) => {
          console.error("UserList - Soft delete error:", error);
          toast.error('Error al mover a papelera', {
            description: error.message,
            richColors: true,
          });
        },
      }
    );
  };
  
```
I confirm the data after the mutation finished is the updated data but my table keeps the same data. 
Is this happening for something I am doing wrong or is a bug?
