### ISSUE TITLE
[BUG] 'useMenu' returns 'menuItems' as 'any[]'

### ISSUE THREAD

**Issue by Tomaszal** [refinedev/refine#5179]
### Describe the bug

`TreeMenuItem` type definition seems to be broken, which results in type of `menuItems` on `useMenu` hook being `any[]`.

### Steps To Reproduce

1. Open the `useMenu` example sandbox: https://codesandbox.io/p/sandbox/github/refinedev/refine/tree/next/examples/core-use-menu
2. Navigate to `src/components/layout/index.tsx`
3. Hover over `menuItems` on line 11, observe the type being `any[]`

### Expected behavior

`TreeMenuItem` type should be as [shown in documentation](https://refine.dev/docs/api-reference/core/hooks/ui/useMenu/#interfaces).

**Comment by Dhoni77** [comment]
Hi @BatuhanW I would like to work on this issue

**Comment by aliemir** [comment]
Hey @Tomaszal, sorry for the issue! Just investigated it. In our build/compilation process if we've imported the types with a path alias they result in `any` since they cannot be resolved. Here in the https://github.com/refinedev/refine/blob/8c2b3be35b0132fc9a7b79287d281a9f922424d0/packages/core/src/hooks/menu/useMenu.tsx#L11 line 11, the `FlatTreeItem` is resolving as `any`. If we can replace this import with a relative one instead of an alias, this issue will be resolved.

**Comment by BatuhanW** [comment]
@Dhoni77 assigned this issue to you, @aliemir added a hint about how to fix it. Looking forward to your PR! 🙌🏼

**Comment by fitrahfm** [comment]
Hi @aliemir, let me know if I can help you to create a PR
