### ISSUE TITLE
[BUG] useInfiniteList pagination is broken

### ISSUE THREAD

**Issue by rwtnb** [refinedev/refine#5832]
### Describe the bug

At [useInfiniteList](https://github.com/refinedev/refine/blob/master/packages/core/src/hooks/data/useInfiniteList.ts#L253) is missing the default value for pageParam, setting `pageParam = preferredPagination.current ?? 1` seems to fix it.

```
queryFn: ({ queryKey, pageParam, signal }) => {
      const paginationProperties = {
        ...prefferedPagination,
        current: pageParam,
      };
```

### Steps To Reproduce

1. define a useInfiniteList hook
```
    const {
        data,
        isError,
        isLoading,
        hasNextPage,
        fetchNextPage,
        isFetchingNextPage,
    } = useInfiniteList<ContactsPage>({
        resource: "contacts",
        meta: {
            fields: ["id", "name", "photo"],
        },
        pagination: {
            pageSize: 20,
            mode: "server"
        },
    });
```

2. Test it, we are using the nestjs-query for our graphql apis
3. You will see that the paging field is not passed as argument for the query, because `paginationProperties.current` is overriden by `pageParam` (always undefined)

### Expected behavior

Pagination to work

### Packages

- @refinedev/core

### Additional Context

I can make a PR, but I'm very new to Refine and Tanstack.
Just want to make sure this is the correct approach.
Thanks!

**Comment by alicanerdurmaz** [comment]
Hello @rwtnb, Thanks for the issue. 

The issue seems to be valid, your solution is good, but we want to investigate more and find the best solution that is compatible with all other packages.

We will debug and get back to you. 👍

**Comment by rwtnb** [comment]
Thanks, for the follow up.
Let me know if I can help with anything else, we're going to production next week.
Our experience with refine so far has been amazing!
You're doing a really good job over there, so good that make want to pay for the enterprise plan.

**Comment by aliemir** [comment]
Pagination for the `useInfiniteList` is calculated internally by checking the current page parameters and the `total` value returned from the data provider (in this case `@refinedev/nestjs-query`). If total is not returned, then there will be issues with the default page params calculations. This can be overwritten by passing `queryOptions.getNextPageParam`. 

But I guess this issue is more related with the initial requests made by `useInfiniteList` rather than the next pages. I investigated the `useInfiniteList` and `@refinedev/nestjs-query` and found that default pagination values are missing from the `dataProvider` exported from the package. 

If we add the default pagination values (say `current = 1` and `pageSize = 10`) the issue will be resolved in some kind.

But I think there's one more issue related with this. `useInfiniteList` is unable to `pagination` prop for the initial pagination values.  🤯 I'll try to investigate more to find a proper solution covering all related cases. 🚀

**Comment by qsoo** [comment]
I'm having the same issue. Here's the version I used.
- React: v18
- @refinedev/core: v4.56.0

I don't like to modify the package internals, so I used a workaround within the data provider(The target to call getList on) to assign 1 when the value of `pagination.current` is undefined.

@aliemir 
Could a future version include a fix for this issue?
