### ISSUE TITLE
[BUG] appendCurrentPathToQuery on Authenticated 

### ISSUE THREAD

**Issue by Masterearth077** [refinedev/refine#5866]
### Describe the bug

<Authenticated appendCurrentPathToQuery={false} fallback={<Navigate to="/login" />}>
    {/* Your routes here */}
</Authenticated>

it not work appendCurrentPathToQuery={false} i do false but it still true or working route to param query after login

### Steps To Reproduce

1. using <Authenticated > 
2. do appendCurrentPathToQuery={false}  on it
3. i put url with Query Param like http://localhost:9777/login?to=%2FContactPublic
4. login
5. it not go welcome page but it still follow to ContactPublic page
6. end

### Expected behavior

it not work appendCurrentPathToQuery={false} i do false but it still true or working route to param query after login

### Packages

import {Authenticated} from "@refinedev/core";

**Comment by aliemir** [comment]
`appendCurrentPathToQuery` tells the `<Authenticated />` component whether to insert `to` parameter or not. If set to `true`, it will redirect and append the current path with `to` parameter to the URL. If set to `false`, current path will not be included in `to` parameter. 

`useLogin` hook will respect the `to` parameter regardless of the `appendCurrentPathToQuery` (they're unrelated) prop of `<Authenticated />`.

If you append `to` to the url manually, then it's best to check and remove `to` manually from URL as well.

I think this is not related with Refine. For this scenario, we'll not make any changes to the `useLogin` for this behavior.

If you think this is related with Refine and should be fixed by the package itself, feel free to re-open with your proposal 🚀
