### ISSUE TITLE
[FEAT] i18n option when using cli to create project

### ISSUE THREAD

**Issue by BlackBearFTW** [refinedev/refine#5918]
### Is your feature request related to a problem? Please describe.

I have to setup i18n next manually each time.

### Describe the thing to improve

I would like the create-refine cli have an option to automatically include i18n-next, so I won't have to set this up manually each time.

**Comment by BatuhanW** [comment]
@BlackBearFTW thanks for the issue. We are open to contributions for this one. We have similar examples with react-router and antd.

**Comment by aliemir** [comment]
Just linked this issue in a PR and I want to clarify the progress on this. Previously, we had i18n option in `create-refine-app` but decided to remove it due to increased complexity and due to the nature of i18n having project specific requirements. Adding this complexity just to handle essential keys that Refine uses wasn't able to justify the required maintenance 😅 

We've added `refine add provider i18n` command to generate a demo `i18nProvider` which makes it easy to integrate with any library and custom implementation. Yet, this command was missing the translation file that includes essential keys that Refine uses by default. In #6196 we're also creating a `locale/en.json` that includes all the keys Refine uses and some additional keys to hint how Refine's i18n keys are generated. 

In the future we'll update this issue when we have any updates 🙏

**Comment by aliemir** [comment]
Improvements related to i18n is released with the latest version of `@refinedev/cli` 🙏
