### ISSUE TITLE
[BUG] Refine app created with CLI infinitely loads but goes to the login path and back to home path and login path then home path etc...

### ISSUE THREAD

**Issue by jackprogramsjp** [refinedev/refine#5988]
### Describe the bug

When I run `pnpm dev`, and I go to the `localhost`, it just keeps spamming `/login` and then `/` and then `/login` etc. Check the gyazo gif.

https://gyazo.com/ddf4cef3fa74d7d1665795d438f33fdd

### Steps To Reproduce

1. Just create a refine app with the CLI npm create-refine-app
2. I used headless and Appwrite

### Expected behavior

It should not be infinitely loading.

### Packages

    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/nextjs-router": "^6.0.0",
    "@refinedev/kbar": "^1.3.6",
    "next": "14.1.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "@refinedev/appwrite": "^6.4.6",
    "uuid": "^9.0.0",
    "js-cookie": "^3.0.5",
    "@refinedev/react-hook-form": "^4.8.14",
    "@refinedev/react-table": "^5.6.6",
    "@tanstack/react-table": "^8.2.6"

**Comment by alicanerdurmaz** [comment]
Hello @jackprogramsjp, I created a new project and it seems to be no issue.

Can you please provide us `authProvider` and `route` implementations?

**Comment by mschinis** [comment]
I have the same issue, I started a project next.js / supabase project. I usually notice this functionality about one hour after the initial login.

I realize my issue is slightly different to the original issue because I'm using Supabase, but I believe it stems from the same bug.

**From debugging it looks like the reason is because**
1. The default `auth-provider.server.ts` is checking if the user is authenticated, from the cookie, which returns `true`, tries to load the resource/page.
2. The default `auth-provider.ts` is checking if the user is authenticated with supabase js client, which returns an empty user object, and redirects to `/login`.


@alicanerdurmaz  I can invite you to the project that you can use to debug if that helps?

**Comment by mschinis** [comment]
@alicanerdurmaz Changing the `auth-provider.server.ts` to the following, seems to fix the issue, but there's probably a better way to fix this issue using the supabase js sdk.

```typescript
import { AuthBindings } from "@refinedev/core";
import { cookies } from "next/headers";

// ADDED
function decodeJWTPayload (token: string) {
  return JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
}

export const authProviderServer: Pick<AuthBindings, "check"> = {
  check: async () => {
    const cookieStore = cookies();
    const auth = cookieStore.get("token");

    // ADDED
    let expiryTimestamp = decodeJWTPayload(auth?.value!).exp * 1000
    let isStoredTokenValid = Date.now() - expiryTimestamp <= 0

    if (auth && isStoredTokenValid) {
      return {
        authenticated: true,
      };
    }

    return {
      authenticated: false,
      logout: true,
      redirectTo: "/login",
    };
  },
};
```

**Comment by alicanerdurmaz** [comment]
@mschinis I could reproduce the bug, thanks for the solutions. It seems valid but I want to investigate more. 

I believe Supabase's SDK has more viable solutions https://supabase.com/docs/guides/auth/server-side/creating-a-client

I will keep inform you.

**Comment by alicanerdurmaz** [comment]
Hello again @mschinis,

I fixed the supabase auth provider and we will release the fix for `create refine-app` as soon as possible, but you can fix your project while waiting for the release.

You can find the finished project [here](https://github.com/refinedev/refine/tree/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase)

keypoints:
- we need to create [`authProviderServer`](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/providers/auth-provider/auth-provider.server.ts) with `"@supabase/ssr"` package. 
- [Supabase middleware](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/utils/supabase/middleware.ts) to handle all cookie processes and refreshing the Auth token.
- Also I did a couple of fixes on `authProviderClient`
 - I have created [supabase client](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/utils/supabase/client.ts) from `"@supabase/ssr"` package.
 - Also I made changes on [`authProvider`](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/providers/auth-provider/auth-provider.ts). You can copy and paste your project to see DIFF in git.
 
 
Please feel free to let me know if you find any issues or if you have any suggestions for improvements to the code.

**Comment by mschinis** [comment]
Hi @alicanerdurmaz , thanks for the quick turnaround. I've implemented your changes in my project and I'll get back to you, once I do a thorough testing.

In general, your approach make sense. Couple of quick comments:
1. There's a small typo `contants.ts` instead of `constants.ts`
2. [Here, the `supabaseBrowserClient.auth.setSession`](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/providers/auth-provider/auth-provider.ts#L23) method returns a promise, but there's no `await`, was this a conscious decision?

**Comment by mschinis** [comment]
I can confirm that your changes solve my issue, thank you @alicanerdurmaz

**Comment by alicanerdurmaz** [comment]
> Hi @alicanerdurmaz , thanks for the quick turnaround. I've implemented your changes in my project and I'll get back to you, once I do a thorough testing.
> 
> In general, your approach make sense. Couple of quick comments:
> 
> 1. There's a small typo `contants.ts` instead of `constants.ts`
> 2. [Here, the `supabaseBrowserClient.auth.setSession`](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/providers/auth-provider/auth-provider.ts#L23) method returns a promise, but there's no `await`, was this a conscious decision?

You are right, we need to await [the `supabaseBrowserClient.auth.setSession`](https://github.com/refinedev/refine/blob/31d52c5c8e88fedd60fd5b1df1c665821b88dd32/examples/with-nextjs-supabase/src/providers/auth-provider/auth-provider.ts#L23). Thanks!

**Comment by alicanerdurmaz** [comment]
Hello again @jackprogramsjp, we released a fix for appwrite. You can see changed files [here](https://github.com/pankod/superplate-core-plugins/pull/396/files).

If you have any questions please feel free to ask.
