### ISSUE TITLE
[BUG] Using Swizzle for AuthPage in Next.js generates code with i18n but the folder hooks is not created

### ISSUE THREAD

**Issue by SadmanYasar** [refinedev/refine#6140]
### Describe the bug

I created a Next.js Refine project and headless UI. Used swizzle to customize the AuthPage and it imports a hook called useTranslate hook:

```js
import React, { useState } from "react";
import {
  useActiveAuthProvider,
  useLink,
  useLogin,
  useRouterContext,
  useRouterType,
  LoginFormTypes,
  LoginPageProps,
} from "@refinedev/core";

import { useTranslate } from "@hooks/i18n"; //Cannot find module '@hooks/i18n' or its corresponding type declarations.
```

Where and how should this be created to fix it?

### Steps To Reproduce

1. Create a Nextjs + Headless UI project from site.
2. Run `npm run refine swizzle`
3. Select AuthPage
4. Go to the generated file called login.tsx in components/pages/auth/components folder
5. You should see an error "Cannot find module '@hooks/i18n' or its corresponding type declarations."

### Expected behavior

It is supposed to add the hooks folder with the useTranslate hook.

### Packages

"@refinedev/cli": "^2.16.21",
"@refinedev/core": "^4.47.1",
"@refinedev/devtools": "^1.1.32",
"@refinedev/kbar": "^1.3.6",
"@refinedev/nextjs-router": "^6.0.0",
"@refinedev/react-hook-form": "^4.8.14",
"@refinedev/react-table": "^5.6.6",
"@refinedev/simple-rest": "^5.0.1",

**Comment by aliemir** [comment]
Hey @SadmanYasar sorry for the issue! This line is missed by the transform function of the swizzle script. As a workaround you can just import the `useTranslate` from `@refinedev/core`. 

The issue is caused by this line:
https://github.com/refinedev/refine/blob/b07e95bbb24aaabed320810cd3c25a7132e172b4/packages/core/src/components/pages/auth/components/login/index.tsx#L5

Same issue is also present in other Auth pages (`Forgot Password`, `Update Password` and `Register`) 

Just by simply updating this import and adding it to the line above (the import line from `@hooks`) the issue will be resolved. Do you want to work on this fix? We'll be happy to see your PR 🚀 

Check out our [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing) on how to get started with the development. Let us know if you need any help ❤️

**Comment by Sarfraz-droid** [comment]
Hey @aliemir , First time contributor to refine here. I've created a PR that fixes the same.

**Comment by swethamanur** [comment]
Hello @aliemir , if this issue is still open, I would like to get started and resolve it .
