### ISSUE TITLE
[BUG][edit page]useFieldArray disappear

### ISSUE THREAD

**Issue by CRC32EX** [refinedev/refine#6276]
### Describe the bug

`useFieldArray` elements sometimes disappear

https://github.com/user-attachments/assets/f8bffdcc-4a99-4730-bc94-88c0480bd91f

### Steps To Reproduce

1. clone repository
```
git clone https://github.com/CRC32EX/refine_bug_report
```

2. install dependencies
```
npm install
```

3. Build
```
npm run build
```

4. Run in production mode
```
npm run start
```

### Expected behavior

`useFieldArray` elements always appear

### Packages

|Name|Version|
|:--|:--|
|@refinedev/cli|2.16.21|
|@refinedev/core|4.47.1|
|@refinedev/devtools|1.1.32|
|@refinedev/inferencer|4.7.0|
|@refinedev/kbar|1.3.6|
|@refinedev/mui|5.14.4|
|@refinedev/nextjs-router|6.0.0|
|@refinedev/react-hook-form|4.8.14|
|@refinedev/simple-rest|5.0.1|

### Additional Context

Running development mode (`npm dev`) is not reproduce this issue.
Only production mode reporuceable.

I also tried [this](https://github.com/refinedev/refine/tree/master/examples/blog-react-hook-dynamic-form) project files.
This project using Next pages router.
This project is not reproduce this issue.

ref: https://github.com/refinedev/refine/issues/5894

**Comment by BatuhanW** [comment]
Hey @CRC32EX thanks for the issue and appreciate the reproducible example! We'll review it soon and get back to you.

**Comment by BatuhanW** [comment]
Hey @CRC32EX I've checked the issue and I don't think this issue is related to Refine directly. I've managed to fix problem by adding a default value. See the diff below:

![Screenshot 2024-08-28 at 15 08 15](https://github.com/user-attachments/assets/16636f5d-9926-4729-b636-2cc675983e88)

Closing the issue, feel free to re-open it with more context if needed.
