### ISSUE TITLE
[BUG] Unable to migrate from useDataGrid to useTable

### ISSUE THREAD

**Issue by borisyordanov** [refinedev/refine#6415]
### Describe the bug

This works fine:
```
  const { dataGridProps } = useDataGrid({
    dataProviderName: 'inspections',
    pagination: {
      pageSize: 50,
    },
    resource: '/v1/companies/',
  });
```

This doesn't
```
  const {
    getHeaderGroups,
    getRowModel,
    getState,
    setPageIndex,
    getCanPreviousPage,
    getPageCount,
    getCanNextPage,
    nextPage,
    previousPage,
    setPageSize,
  } = useTable<InspectionCompany>({
    columns,
    refineCoreProps: {
      dataProviderName: 'inspections',
      pagination: {
        pageSize: 50,
      },
      resource: '/v1/companies/',
    },
  });
  ```
![image](https://github.com/user-attachments/assets/a7857d61-7f44-46d1-aeaa-2412a532a1bf)

### Steps To Reproduce

Unfortunately, I was unable to create a minimal reproducible example

### Expected behavior

refineCoreProps that work for data grid should work for react table

### Packages

    "@refinedev/core": "^4.49.1",
    "@refinedev/mui": "^5.15.1",
    "@refinedev/react-router-v6": "^4.5.8",
    "@refinedev/react-table": "^5.6.13",
    "@refinedev/simple-rest": "^5.0.5",
    "@tanstack/react-table": "^8.20.5",

**Comment by aliemir** [comment]
Hey @borisyordanov, the code looks good and it should work 🤔 Guessing from the error, it looks like an error originating from the data provider, can you check if there are any requests sent before the error? Also can you check with `useList` or `useTable` from `@refinedev/core` to see if the issue persists with them?

**Comment by borisyordanov** [comment]
@aliemir No request are made if I use useTable from '@refinedev/react-table' (I checked the network tab in dev tools)

if I use useTable from '@refinedev/core` like so I get data without issues

```
  const { tableQueryResult } = useTable<InspectionCompany>({
    dataProviderName: 'inspections',
    pagination: {
      pageSize: 50,
    },
    resource: '/v1/companies/',
  });
```
If I use `useList` like so I get data without issues

```
  const { data } = useList({
    dataProviderName: 'inspections',
    pagination: {
      pageSize: 50,
    },
    resource: '/v1/companies/',
  });
  ```

**Comment by borisyordanov** [comment]
More troubleshooting steps I tried. I updated all packages to the latest version
```
    "@refinedev/core": "^4.55.0",
    "@refinedev/mui": "^5.21.0",
    "@refinedev/react-router-v6": "^4.6.0",
    "@refinedev/react-table": "^5.6.13",
    "@refinedev/simple-rest": "^5.0.8",
    "@tanstack/react-table": "^8.20.5",
```

I tried using refine's router-based fetching and declared this resource in my root `Refine` provider.

```
        {
          list: '/manage/inspections/companies',
          meta: {
            label: 'Companies',
          },
          name: '/inspections/v1/inspection-companies',
        },
```
Again everything works except `@refinedev/react-table`

**Comment by borisyordanov** [comment]
@aliemir 

> do you have any custom definitions in refineCoreProps.queryOptions?

>  Is there a chance that this resource is queried before useTable call with useList (or similar) and altered the response?

Can you suggest how I can test this? Your library controls when things are queried, doesn't it? In my route there are no other async resource so no other requests are made.

> BTW, did you tried sending empty columns to see if there are any issues with column definitions?

I tried, it didn't change anything.

**Comment by aliemir** [comment]
For the query options, I wanted to make sure if there are any calls made to the same resource which can be used by the `useTable` from cache. Cache may be broken if the previous call had `queryOptions.select` method to customize the response. If there are no prior calls then we can say that this is not the case 😅 

Can we check if there are any conflicts between installed versions? We had a small update in `@refinedev/react-table` last month which requires the latest `@refinedev/core` but looks like peer dependency is not updated properly. If you can remove `node_modules` and the lock file (if not an issue for you) and re-install, we can make sure consistent versions are installed 🙏 

I've also tested in my local with your versions (especially with `@tanstact/react-table` as latest) but didn't had any issues with our examples 🤔 

This might be a dual outdated version issue judging by the screenshot of the error, `@refinedev/react-table` might be using an outdated version instead of the latest `@refinedev/core`. Let me know if you can delete `node_modules`, the lock file and re-install again 🙏

**Comment by borisyordanov** [comment]
@aliemir I started going through your source code and noticed [the useTable hook](https://github.com/refinedev/refine/blob/master/packages/react-table/src/useTable/index.ts) is actually quite simple (and small).

I ended up copying your package in my monorepo and now things work. I can only deduce that the npm package is not published correctly?
