### ISSUE TITLE
Pagination for usetable hook

### ISSUE THREAD

**Issue by Majmani98** [refinedev/refine#6466]
### Describe the bug

I want to paginate a table(client side) by passing the data array directly to the usetable hook instead of using the in built uselist hook that the table uses in refine

### Steps To Reproduce

useTable({columns,data,refineCoreProps:{pagination:{mode:’client’,pageSize:10}}})

### Expected behavior

pagination should work

### Packages

@refinedev/react-table

**Comment by alicanerdurmaz** [comment]
Hello @Majmani98,

Unfortunately, `useTable` wasn't designed that way, but we can handle it with a simple workaround.

Option 1:
Since `useTable` is designed to work with the API, filters, and sorters won’t work with this method.

```tsx
import { useTable } from "@refinedev/react-table";
import { getPaginationRowModel } from "@tanstack/react-table";

useTable<IPost>({
    getPaginationRowModel: getPaginationRowModel(),
    columns,
    data: mockData,
    manualPagination: false,
    pageCount: mockData.length / 10,
    refineCoreProps: {
      pagination: {
        mode: "off",
      },
      queryOptions: {
        enabled: false,
      },
    },
```

Option 2 (Refine way):

You can create a new `dataProvider` called "localDataProvider". This `dataProvider` would return data from JSON based on the "resource" you provide, and it would keep the data only on the client side. You could also add simple filtering and sorting functions to this data provider.

These documents will be useful for guidance.
- [Multiple Data Provider documentation](https://refine.dev/docs/data/data-provider/#multiple-data-providers)
- [Creating a Data Provider tutorial](https://refine.dev/tutorial/essentials/data-fetching/intro/#creating-a-data-provider)
