### ISSUE TITLE
[FEAT] Breadcumbs configure displayed elements

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6497]
### Describe the bug

It appears that the breadcrumb component doesn't display anything when the array contains only a single element. This undermines the consistency of the layout, as I would like to maintain a consistent breadcrumb style across all pages, even when there is only one breadcrumb item. Could you kindly add a property to define the minimum number of elements required for the breadcrumb to be displayed?

### Steps To Reproduce

```js
import { Toolbar } from "@mui/material";
import { useBreadcrumb } from "@refinedev/core";
import { Breadcrumb, ThemedLayoutV2 } from "@refinedev/mui";
import { Outlet } from "react-router-dom";

const Header = () => {
  const breadcumb = useBreadcrumb();
  console.log(breadcumb);

  return (
    <Toolbar>
      <Breadcrumb showHome meta={{ projectId: "123" }} key={1} />
    </Toolbar>
  );
};

const SidebarLayout = () => (
  <ThemedLayoutV2 Header={Header}>
    <Outlet context={{ component: "main", sx: { flex: 1 } }} />
  </ThemedLayoutV2>
);

export default SidebarLayout;
```

### Expected behavior

See above.

### Packages

Latest.

**Comment by alicanerdurmaz** [comment]
Hello, @aress31, Thanks for the detailed explanation! 

Yes, It would be great! Do you want to work on this?

Source code:
https://github.com/refinedev/refine/blob/9ecbd45fe0b0f4e09c5389a9095691c6511a4445/packages/mui/src/components/breadcrumb/index.tsx#L44-L45

**Comment by aress31** [comment]
Sure

**Comment by alicanerdurmaz** [comment]
We discussed with the core team and decided that the implementation would be better as follows:

1. `<Breadcrumb />` should take a new prop as `minItems`(or better name) and the [breadcrumbs.length === 1](https://github.com/refinedev/refine/blob/master/packages/mui/src/components/breadcrumb/index.tsx#L44) check should be compared with this new prop.

2. new prop's type should be added to [@refinedev/ui-types](https://github.com/refinedev/refine/blob/master/packages/ui-types/src/types/breadcrumb.tsx#L1)
```ts
/** 
* Minimum number of breadcrumb items required for rendering. Component won't render if items * are less than this number. 
*/
minItems?: number;
```
3. All UI packages should be updated
- https://github.com/refinedev/refine/tree/master/packages/mui/src/components/breadcrumb
- https://github.com/refinedev/refine/tree/master/packages/core/src/hooks/breadcrumb
- https://github.com/refinedev/refine/tree/master/packages/antd/src/components/breadcrumb
- https://github.com/refinedev/refine/tree/master/packages/mantine/src/components/breadcrumb
- https://github.com/refinedev/refine/tree/master/packages/chakra-ui/src/components/breadcrumb

4. All tests should be updated. If possible, it should be implemented in the `@refinedev/ui-tests` package; otherwise, it can be implemented in the package's own test file.

5. All documentations should be updated.

---

If I missed anything, please feel free to update it 🚀

**Comment by aress31** [comment]
@alicanerdurmaz, I’ve made further updates to the PR, and it’s now ready for your review. However, I have a few points:

I’m unsure how to implement the guidance from [this file](https://github.com/refinedev/refine/tree/master/packages/core/src/hooks/breadcrumb) or if I’m missing something in your approach. Any clarification or guidance would be appreciated.
Some tests are failing, and I suspect it’s because I haven’t yet addressed the issues mentioned in [this file](https://github.com/refinedev/refine/tree/master/packages/core/src/hooks/breadcrumb). Could you kindly review that part?
I’m finding it difficult to work on the PR as I don’t have full visibility of the changes. I’ve followed the [contributing guide](https://refine.dev/docs/guides-concepts/contributing/), but running pnpm dev --scope @refinedev/mui doesn’t start a local server where I can preview the changes. Could you provide guidance on this? It would also be helpful if the guide could be improved for future contributors.

**Comment by aress31** [comment]
@alicanerdurmaz any help with:

> I’m finding it difficult to work on the PR as I don’t have full visibility of the changes. I’ve followed the [contributing guide](https://refine.dev/docs/guides-concepts/contributing/), but running pnpm dev --scope @refinedev/mui doesn’t start a local server where I can preview the changes. Could you provide guidance on this? It would also be helpful if the guide could be improved for future contributors.

**Comment by BatuhanW** [comment]
> @alicanerdurmaz / @BatuhanW any help with:
> 
> 
> 
> > I’m finding it difficult to work on the PR as I don’t have full visibility of the changes. I’ve followed the [contributing guide](https://refine.dev/docs/guides-concepts/contributing/), but running pnpm dev --scope @refinedev/mui doesn’t start a local server where I can preview the changes. Could you provide guidance on this? It would also be helpful if the guide could be improved for future contributors.

@aress31 You can start base-mui example the same way to see your changes.

**Comment by aress31** [comment]
@BatuhanW sorry for being a bit slow but what would be the exact command that I need to run?

**Comment by OmkarBansod02** [comment]
> @BatuhanW sorry for being a bit slow but what would be the exact command that I need to run?

Hey @aress31 I guess you need to run `pnpm run dev --scope @refinedev/mui --scope @examples/base-mui ` command.

**Comment by AlirezaHadad** [comment]
Hi, I’d like to work on this issue. Could you assign it to me?
