### ISSUE TITLE
[BUG] useForm Loading State

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6529]
### Describe the bug

When disabling the query via `queryOptions: { enabled: action !== "create" }` the loading states seem to return `true` which is counter intuitive:

- `isLoading`
- `isFetching`
- `isRefetching`

### Steps To Reproduce

```js
const useFormData = ({ action, id }) => {
  const [formData, setFormData] = useState([]);

  const {
    query: {
      data: { data = [] } = {},
      isSuccess,
      isLoading,
      isFetching,
      isRefetching,
    },
    onFinish,
    formLoading,
  } = useForm({
    id,
    action,
    queryOptions: { enabled: action !== "create" },
  });

  useEffect(() => {
    if (isSuccess) setFormData(data);
  }, [isSuccess, data]);

  return {
    formData,
    // As you can see I have to add the extra condition `&& action !== "create"`
    loadingForm:
      (isLoading || isFetching || isRefetching) && action !== "create",
    formLoading,
    onFinish,
  };
};
```

### Expected behavior

Should return `false` by default for all loading states since the query don't get executed due to the condition.

### Packages

Latest

**Comment by BatuhanW** [comment]
@aress31 it's intended behaviour for react-query, not related to Refine. We appreciate anyone who creates issues for Refine. I want to mention that we spend time for **every** issue, so please care more before creating issues. We have AI Chatbot in our documentation, also discussions section for your ideas and questions. Issues should be created if you are absolutely sure the problem is with Refine.
